version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6.14.0

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - yarn
      - checkout
      - run: yarn config set cache-folder /tmp/yarn
      - run: yarn
      - run: yarn --cwd functions
      - run: yarn lint
      - save_cache:
          key: cache
          paths:
            - /tmp/yarn
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  deploy:
    docker:
      - image: circleci/node:6.14.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: echo $DOTENV | base64 --decode > .env
      - run: yarn deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  default:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test