version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.14.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn
      - run: yarn --cwd functions
      - run: yarn lint
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  deploy:
    docker:
      - image: circleci/node:6.14.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - echo $DOTENV | base64 --decode > .env
      - yarn deploy --token $FIREBASE_TOKEN
